---
apiVersion: v1
kind: Service
metadata:
  name: vip-control-dns
  labels:
    app: control-dns
  annotations:
    metallb.universe.tf/allow-shared-ip: host
spec:
  selector:
    app: control-dns
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: control-dns
  labels:
    app: control-dns
spec:
  hostNetwork: false
  containers:
  - name: control-dns
    image: apnex/control-dns
    volumeMounts:
    - name: config-volume
      mountPath: /usr/lib/node_modules/bind-cli/lib/records.json
      subPath: records.json
  volumes:
    - name: config-volume
      configMap:
        name: dns-records
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-records
  namespace: default
data:
  records.json: |
    [
    	{
    		"name": "esx01.core.syd",
    		"addr": "10.30.0.15"
    	},
    	{
    		"name": "esx02.core.syd",
    		"addr": "10.30.0.16"
    	},
    	{
    		"name": "esx03.core.syd",
    		"addr": "10.30.0.17"
    	},
    	{
    		"name": "esx04.core.syd",
    		"addr": "10.30.0.18"
    	},
    	{
    		"name": "esx05.core.syd",
    		"addr": "10.30.0.19"
    	},
    	{
    		"name": "control.core.syd",
    		"addr": "10.30.0.30"
    	},
    	{
    		"name": "factory.core.syd",
    		"addr": "10.30.0.31"
    	},
    	{
    		"name": "vcenter.core.syd",
    		"addr": "10.30.0.32"
    	},
    	{
    		"name": "vcenter.lab01.syd",
    		"addr": "10.30.0.110"
    	},
    	{
    		"name": "esx11.lab01.syd",
    		"addr": "10.30.0.111"
    	},
    	{
    		"name": "esx12.lab01.syd",
    		"addr": "10.30.0.112"
    	},
    	{
    		"name": "esx13.lab01.syd",
    		"addr": "10.30.0.113"
    	},
    	{
    		"name": "esx14.lab01.syd",
    		"addr": "10.30.0.114"
    	},
    	{
    		"name": "nsxm01.lab01.syd",
    		"addr": "10.30.0.117"
    	},
    	{
    		"name": "nsxe01.lab01.syd",
    		"addr": "10.30.0.118"
    	},
    	{
    		"name": "avic01.lab01.syd",
    		"addr": "10.30.0.119"
    	}
    ]
